### ISSUE TITLE
Links too sensitive in comments

### ISSUE THREAD

**Issue by devm33** [weiran/Hackers#131]
As of a recent release links in comments became too sensitive so that it's difficult to scroll because links keep opening.

I'm guessing this was a tweak to improve their sensitivity because I remember previously links were fairly difficult to press.

Is there a way to prevent the click on links when scrolling?

**Comment by JeffreyCA** [comment]
Something seemed to have changed in iOS 13.

Links should be triggered on _tap release_ not on _tap down_

**Comment by weiran** [comment]
Thanks for the bug reports, this will be fixed once 4.1.1 is approved for release.
