### ISSUE TITLE
Doesn't load all comments if there are a lot

### ISSUE THREAD

**Issue by weiran** [weiran/Hackers#146]

**Comment by weiran** [comment]
Looks like this requires a modification to HNScraper.

**Comment by robbiet480** [comment]
[This](https://news.ycombinator.com/item?id=23223219) is an example of the issue. You’ll see it only loads the first tree of comments after dang’s tree. As he notes, the top two trees are so long you must click More in the web UI. 

Hackers should recursively get comments until there are no more to be had.

**Comment by weiran** [comment]
Yep I agree. I've been looking at your UltraHN library for inspiration on the best way to get comments from HN. It still looks like HTML scraping is the best option unless I want to add a Firebase dependency to use their API properly.
