### ISSUE TITLE
Login UI doesn't layout right with iPad split view

### ISSUE THREAD

**Issue by weiran** [weiran/Hackers#147]
Could be time to replace this with a native UI anyway.

**Comment by ianleon** [comment]
I had no idea that it wasn’t native.

**Comment by weiran** [comment]
It is native iOS, I meant I use a third party lib https://github.com/alexaubry/BulletinBoard but I think this UI should be native to the app.

**Comment by weiran** [comment]
Resolved with https://github.com/alexaubry/BulletinBoard/pull/173 and version BulletinBoard release 4.1.1. Will be released in Hackers 4.3.
