### ISSUE TITLE
Using autofill in login form only fills username

### ISSUE THREAD

**Issue by delreluca** [weiran/Hackers#156]
When using the autofill option on the username field only the username gets filled in.

If I use the option on the password field both fields get filled.

Since I can reproduce with 2 different password managers (KeePassium and Strongbox) it seems to be an iOS integration issue.

**Comment by weiran** [comment]
Thanks for the report. I'm thinking about redoing the login flow anyway so will take this into consideration when doing so.

**Comment by InsanelyHarsh** [comment]
I would like to take this issue

**Comment by InsanelyHarsh** [comment]
Is there any other task, on which I could work?
I am a beginner, starting an open-source journey.

**Comment by InsanelyHarsh** [comment]
Great! 
Is there any other issue on which I can work?
