### ISSUE TITLE
Truncated URLs in comments are dead links

### ISSUE THREAD

**Issue by Braveatom** [weiran/Hackers#158]
If a link in the comments is truncated due to its length, the URL it tries to load on click is the truncated URL - resulting in a dead link / 404.

example - this HN story https://news.ycombinator.com/item?id=23291155

contains the links - https://www.alamy.com/highway-interchange-or-multi-layered-h and https://www.bizjournals.com/austin/news/2018/12/15/a-primer-  both of which are dead links.

screenshot attached

![IMG_5515 2](https://user-images.githubusercontent.com/1375454/82881914-3ab2c200-9f38-11ea-831d-78b1f2860b94.png)

**Comment by weiran** [comment]
Thanks for the report

**Comment by weiran** [comment]
Fixed in 4.3
