### ISSUE TITLE
Share button behavior changed recently

### ISSUE THREAD

**Issue by szhu** [weiran/Hackers#176]
Previously, if I clicked into a discussion and tapped the share icon, I would get options for sharing the discussion.

Recently, it looks like the button behavior changed. Now when I tap the share icon, I get options for sharing the linked website.

I'm not sure if this is a bug or if it was intended to be a feature. If the latter, what's the recommended way for me to get or share the link to discussions?

**Comment by weiran** [comment]
Hi @szhu,

Thanks for reporting this. It looks like a regression in 4.3, so I'll get a 4.3.1 hotfix out to revert to the previous behaviour.

In 4.4 it offers you the choice between sharing the article or Hacker News link.

**Comment by szhu** [comment]
Confirmed fixed in the app. Thank you!
