### ISSUE TITLE
iOS 14, default browser set to Chrome

### ISSUE THREAD

**Issue by bradleyg** [weiran/Hackers#185]
When you set your [default browser to Chrome](https://www.macrumors.com/how-to/google-chrome-default-browser-ios/) in iOS 14, the "article link" within each news story doesn't work. You can click it, but nothing happens ([see video](https://storage.bradleyg.dev/hackers-app-default-browser.mp4)).

Setting the default browser within iOS back to Safari fixes this issue.

**Comment by MattGHarvey** [comment]
Same issue if Edge is set as default browser.

**Comment by weiran** [comment]
Thanks for the reports. Aiming to get this fixed with #184 and a few other changes.

**Comment by weiran** [comment]
Fixed in 4.4.2.
