### ISSUE TITLE
No ability to get back password

### ISSUE THREAD

**Issue by Codingprodigy-tech** [weiran/Hackers#196]
If you've forgotten your password there's no way to get it back and no way of recreating your account

**Comment by weiran** [comment]
Hi @Codingprodigy-tech, this is a third party app for Hacker News so it doesn't manage the accounts (all the app knows about is your username and session token).

However I think I'll add links to the Hacker News [create account](https://news.ycombinator.com/login) and [password recovery](https://news.ycombinator.com/forgot) pages in the app.
