### ISSUE TITLE
Right pane on iPad is initially light in dark mode

### ISSUE THREAD

**Issue by delreluca** [weiran/Hackers#201]
See screenshot: ![image](https://user-images.githubusercontent.com/35895923/118171043-23136880-b42b-11eb-96be-0f91f1679982.jpeg)

After choosing a submission it turns dark again.

**Comment by weiran** [comment]
Hi @delreluca, thanks for the report, will fix this in the next release.

**Comment by pastre** [comment]
Is this resolved? If not, I can open a PR :)

**Comment by delreluca** [comment]
Yes, it is resolved 🙂 but thanks

**Comment by pastre** [comment]
Cool. It might be a good idea to close this issue, then :)
