### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by mulhoon** [weiran/Hackers#206]
Hi, awesome app! Used it daily for a long time. 

Is there a way to enable dark mode without setting my whole OS to dark mode? I know this used to be available and then was removed.

Thanks
Nic

**Comment by InsanelyHarsh** [comment]
I would like to take on this task.

**Comment by mulhoon** [comment]
Shame about this. I feel dark mode on any app should be a per-app choice, not a system choice. 

Great app nevertheless. Keep up the great work!
