### ISSUE TITLE
Hackers app prompts for local network device permission on fresh install

### ISSUE THREAD

**Issue by k-jackson** [weiran/Hackers#236]
What:
 - The Hackers app prompts the user for access to see/connect to local network devices.
![hackers_app_prompt](https://user-images.githubusercontent.com/2794246/172030336-e4914b0e-ad91-47c0-a211-a2a36f965d79.png)

How:
- Opening the app for the first time on a fresh install, or when opening the app on an existing install. 

When:
- The prompt first appeared (to my knowledge) on June 4th, 2022.

Where:
- iPhone Xs, iOS 15.5

I'm not sure why an HN reader app needs to see local network devices. I've been using the app for years, and I haven't seen this prompt until today.

**Comment by weiran** [comment]
Very strange, I've never seen this happen and can't replicate. Please reopen if you still get this request with the latest version.
