### ISSUE TITLE
"Couldn't connect to Hacker News" Error when loading Top

### ISSUE THREAD

**Issue by Ferlow** [weiran/Hackers#243]
###
Version: 4.7.4

### Description

The _Top category_ doesnot load and shows _"Couldn't connect to Hacker News"_. Other categories load fine.

![photo_2022-09-21_14-38-55](https://user-images.githubusercontent.com/60618121/191520342-4855fe51-ec60-47d9-8d78-e2d7e42e0f0e.jpg)

### Steps to Reproduce

1. Load Hackers App
2. Wait a few seconds
3. Error shows and page remains blank

**Expected behavior:** Top posts load.

**Actual behavior:** Top posts didn't load.

**Comment by weiran** [comment]
This is because the link submitted for the BetterBird post is `https://www.betterbird.eu/##` with a double hash at the end. For some reason Swift URL parsing rejects this even though it's a valid URL.
