### ISSUE TITLE
Posts don’t load in 4.7.5 on iOS 16.0.2

### ISSUE THREAD

**Issue by syradar** [weiran/Hackers#245]
Posts don’t load. No error is shown, just a spinner.

Tried reinstalling the app.

**Steps to reproduce:**

- Install the latest iOS update 16.0.2
- Open Hackers

![0B6A8524-EC9E-4805-92BF-753754AA5DA6](https://user-images.githubusercontent.com/10453338/192685069-a22eb525-5612-47a3-b5b4-a4e487affcfa.png)

**Comment by Method5440** [comment]
Same on 16.0

**Comment by andreapavoni** [comment]
I have the same problem on my device.

**Comment by megeek** [comment]
Same issue for me on 15.6.1

**Comment by weiran** [comment]
Fixed in 4.7.6 which is available now.

**Comment by andreapavoni** [comment]
It looks like it’s happening again with 4.7.8.
