### ISSUE TITLE
App no longer seems to be working

### ISSUE THREAD

**Issue by jftuga** [weiran/Hackers#247]
App version 4.7.5 on iOS 15.7, iPhone 12.

When I open the app, I just see the spinning status icon in the center of the app  - like it's waiting for something.  I am not logged into the HN site. How can I fix this?

**Comment by syradar** [comment]
Try going to the AppStore page for Hackers. There is a 4.7.6 update released a few days ago

**Comment by jftuga** [comment]
> Try going to the AppStore page for Hackers. There is a 4.7.6 update released a few days ago

This fixed my issue.  Thank you.
