### ISSUE TITLE
Unable to connect to Hacker News

### ISSUE THREAD

**Issue by shot-codes** [weiran/Hackers#255]
As of this morning I'm seeing the following:

![image](https://user-images.githubusercontent.com/43202406/201907655-b37adaeb-dbe4-43da-a6af-7f8c8a9708e5.png)

**Comment by matthieugouel** [comment]
Seems to work again since today

**Comment by s-h-o-t** [comment]
Correct :)

**Comment by weiran** [comment]
This was fixed by #256 and 4.8.9 with those changes was released earlier this week :).

**Comment by mattnotmitt** [comment]
Seems to have gone walkies again

**Comment by Braveatom** [comment]
The last day or so, this seems to have regressed unfortunately - it’s back to no connection

**Comment by Braveatom** [comment]
This appears to be working again. How bizarre, but happy!

**Comment by JeffreyCA** [comment]
It's not working for me on 4.7.10

**Comment by Braveatom** [comment]
> It's not working for me on 4.7.10

Likewise -  very odd!

**Comment by s-h-o-t** [comment]
I'll re-open this as the issue seems to persist. Checking my own client now, while I don't receive the "couldn't connect to Hacker News" popup, I just have an infinite loading spinner. v4.7.10

**Comment by sambehrens** [comment]
I'm also having this issue with the infinite loading spinner and no error messages on v4.7.10

I deleted the app data and redownloaded to make sure it wasn't just me and it still loads infinitely.

**Comment by alexcroox** [comment]
Mine seems to work at random times in the day which makes me think it’s an API availability issue?

**Comment by Braveatom** [comment]
As of this morning this is working here - only used it for a few minutes but all ok so far.

**Comment by alexcroox** [comment]
Also confirmed working after today’s update, thank you!

**Comment by shot-codes** [comment]
Fixed for me as well. I'll leave it open for Weiran to close when he deems fit.

**Comment by sambehrens** [comment]
> Fixed for me as well. I'll leave it open for Weiran to close when he deems fit.

Fixed for me as well! Thanks
