### ISSUE TITLE
Icons disappeared

### ISSUE THREAD

**Issue by syradar** [weiran/Hackers#258]
On 4.7.11 the favicons don’t load :(
![00C279BC-08A6-4E5A-ACE2-C939045F3F3E](https://user-images.githubusercontent.com/10453338/216809553-4b2a7e41-4109-45c4-b8e5-cb03c7058c73.png)

**Comment by weiran** [comment]
Thumbnails rely on [an API](https://github.com/weiran/image-fetcher), who's hosting account has reached its spending limit this month. It will reset tomorrow (6 Feb) and I'll look into reducing its cost.

**Comment by syradar** [comment]
Maybe some URL caching with a longish TTL might work. Either in the app but perhaps preferably in the API.

**Comment by syradar** [comment]
Oh and feel free to close

**Comment by weiran** [comment]
It's something else on that account causing the high cost, the thumbnail API has caching and 90% of requests are served from the cache :).

I will keep this issue open until it's fixed. Thanks for reporting.
