### ISSUE TITLE
Empty comments

### ISSUE THREAD

**Issue by syradar** [weiran/Hackers#260]
Found comments without any text in them. They might be deleted/banned. I could not find them in the browser https://news.ycombinator.com/item?id=34657655

4.7.11

![AF5C259F-63C0-49C8-82EC-CA74056A39C6](https://user-images.githubusercontent.com/10453338/216811620-02e27125-36ed-42e4-97d9-92c4fb614ad1.png)

**Comment by weiran** [comment]
That link has gone from 840 comments in your screenshot down to 243 now! I assume some major comment moderation happened, but it's hard to find any similar comments now.
