### ISSUE TITLE
build ios 16 failed 

### ISSUE THREAD

**Issue by lzzk** [weiran/Hackers#262]
i build it for my iphone14, but it didn't work. the log says：PromiseKit submodule update failed，i think the swiftPM is not work.
so i manually install promiseKit, it worked in simulated environment, however it can't work in my phone, it crashed and the log: it didn't find promiseKit. it bothers me serval days, any help i will appreciate.

**Comment by weiran** [comment]
This is building fine on latest Xcode and iOS versions, it's likely an environment issue on your end.
