### ISSUE TITLE
HTML Code seen in Comments

### ISSUE THREAD

**Issue by JeffreyCA** [weiran/Hackers#40]
I'm seeing these HTML code like this at the end of every comment in the app.

![img_a9e43a49f99d-1](https://user-images.githubusercontent.com/9157833/44890607-f2099e80-aca8-11e8-93f2-acfeb18ce9d0.jpeg)

**Comment by weiran** [comment]
I can't reproduce, can you send an example.

**Comment by JeffreyCA** [comment]
![img_10a7ff6e2e97-1](https://user-images.githubusercontent.com/9157833/45257585-8c877300-b376-11e8-9d9f-fc0fdb4ae8fd.jpeg)

**Comment by JeffreyCA** [comment]
@weiran any updates on this?

**Comment by weiran** [comment]
@JeffreyCA I'm unable to reproduce it on my devices, I'm wondering if you're unable to pull the config update from GitHub. Can you try this link on your device: https://raw.githubusercontent.com/weiran/libHN/master/Source/hn.json

**Comment by JeffreyCA** [comment]
I can access it. Strange, I upgraded to iOS 12 and the problem is gone now.

**Comment by JeffreyCA** [comment]
Hmm I'm still seeing it on this article: https://news.ycombinator.com/item?id=18030355

**Comment by weiran** [comment]
Yep I can see it with that one, thanks for the report.
