### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by robbiet480** [weiran/Hackers#44]
@weiran Any thoughts on implementing push notifications? I think it's one of the key things missing in any Hacker News app. The simple v1 can just be notifications when a story is >= X points. I'm willing to write the backend for this, probably just something with Firebase Cloud Messaging so that we can use topics to determine what devices to send notifications to.

As another option that wouldn't require a backend service, we can build something similar to what GitHawk does, where it uses background fetch to trigger notifications by fetching data from GitHub. The nice side effect of this would be we can cache data in the background so that the app always has fresh data. More info about GitHawk's implementation is available [here](https://blog.githawk.com/2018/10/02/Notifications-and-Background-Fetch.html).

**Comment by weiran** [comment]
I like the idea of using local notifications when there's a post over a voting threshold to avoid a server-side element and having to deal with certificates. Some ideas below:

* Fetch top posts periodically (every 2-4 hours)
* Send a local notification of the top post if it's passed a voting threshold (>200 perhaps)
* Fetch the post thumbnail and add to the notification
* Avoid duplicate notifications by storing notified posts locally
* Take you directly to the comments view when tapping on a notification

**Comment by robbiet480** [comment]
@weiran Generally sounds good, but background fetch happens about every 15 minutes, sometimes less if you use the app a lot. I was thinking that we would notify for every post that passed the threshold between fetches. I would also want to make the points threshold configurable. 

As for the notification itself, i'm thinking i'll do a UNNotificationAttachment with the thumbnail image as well as a content extension to show a preview with the same details as the PostTitleView while also having two action buttons, one to open comments and one to open the link itself.
