### ISSUE TITLE
Asking Hacker News to add a apple-app-association-file

### ISSUE THREAD

**Issue by robbiet480** [weiran/Hackers#50]
Hey @weiran, I pinged you on Twitter but realized it would probably be good to also make an issue about this...

I'm working on some major improvements to Hackers, one of them being authentication so that you can up and down vote stories and comments. It's working great already, but for that extra sparkle effect I want to get [Password Autofill](https://developer.apple.com/documentation/security/password_autofill/) up and running. However, to do that we need to have the Hacker News team [add a `apple-app-association-file` to their domain](https://developer.apple.com/documentation/security/password_autofill/setting_up_an_app_s_associated_domains). I think that they would happy to do it, especially since the file can allow any number of other apps to also get the same experience just by adding the bundle ID. And i'll add that even if Hackers died sometime in the future (not that I expect it to!) it wouldn't hurt any users of the app or otherwise in any way. It's much like a `robots.txt` file, some apps will check for it and everyone else doesn't even know it exists really.

I thought i'd check with you before reaching out to the team on the off chance you wanted to handle it. If not, I would happily do it and it would perhaps even get a better response because I am myself a YC founder...

Anyway, let me know, will leave this open until I hear back.

BTW, the file looks like this and placed at `https://news.ycombinator.com/apple-app-site-association` (or `https://news.ycombinator.com/.well-known/apple-app-site-association`):

```json
{
  "webcredentials": {
    "apps": [
      "2KB59GPA9B.com.weiranzhang.Hackers"
    ]
  }
}
```

**Comment by weiran** [comment]
Closing this, let me know if you have any traction on HN adding an association file to their site.
