### ISSUE TITLE
Duplicate stories

### ISSUE THREAD

**Issue by JeffreyCA** [weiran/Hackers#54]
I see duplicate entries when scrolling multiple pages down.

![a56b01a5-a46e-43b0-a28d-576c675c37de](https://user-images.githubusercontent.com/9157833/48587319-aefeb500-e900-11e8-80e7-01739d2b3df2.jpeg)

**Comment by weiran** [comment]
Thanks for the feedback. I believe this may be related to Hacker News changing the ranking of posts and then returning duplicates if a post from the current page drops below the cutoff to the next page. 

I can't reproduce it this testing on live data (fetching the next page recently from the previous one). Feel free to reopen this if you can regularly replicate and I'll have a look again.

**Comment by JeffreyCA** [comment]
It happens quite regularly. In my case I read a few stories, which can take several minutes, go back, then scroll down the list of stories, continue. This is a pretty natural way of using the app, which is different from continuously scrolling down in one go when you tried to reproduce it.

Can you take a look again?
