### ISSUE TITLE
Add option to disable thumbnails

### ISSUE THREAD

**Issue by jontaydev** [weiran/Hackers#55]
What do you think about adding an option to disable thumbnails? I find them to be distracting, because they are usually too blurry, irrelevant, and load very slowly. Even the "Y" icon used for Ask HN looks terrible and pixelated. 

I don't have any suggestions for what an alternative UI would look like. I would be fine with the default Safari icon for everything though.

Thanks!

**Comment by weiran** [comment]
Thanks for the feedback! You're right that the thumbnails do take considerable processing and time (have to fetch the image, resize to thumbnail size, cache it locally), so I think it is a viable option.
