### ISSUE TITLE
Support dynamic font sizes

### ISSUE THREAD

**Issue by weiran** [weiran/Hackers#64]

**Comment by harveyphan** [comment]
Great work mate! 

I am waiting long time for this feature. Because my eyes is getting worse especially seeing the HK news on iphone.

**Comment by weiran** [comment]
I should've added this months ago, it's currently in 3.6.1 which is waiting for review.

**Comment by weiran** [comment]
Resolved by #65

**Comment by weiran** [comment]
@harveyphan update is out, let me know if you have any issues with it.
